### PR TITLE
This PR fixes the "Hybrid" filter issue not working properly. Resolves #833.

### LINKED ISSUE #833: "Hybrid" Filter not Working Properly
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Chrome
  - operating system: Windows 11 Home
  - version: 23H2

**STEPS TO REPRODUCE**: 
1. Go to https://peviitor.ro/#/rezultate
2. Filter by "Fedex".
3. Filter by "Hibrid".

**EXPECTED RESULTS**:
The page displays all hybrid jobs available from Fedex (1).

**ACTUAL RESULTS**:
The page displays the "Ups! Căutarea nu are rezultat" error message.

image

image

### PR DESCRIPTION
**Pull request by CbnMarian**
What I've Changed:

   - Added a new checkbox for the **"Hybrid"** filter that now correctly links to the **database entries**.
   - Fixed the discrepancy between the term **"Hibrid**" used in the UI and "Hybrid" in the database, ensuring users can correctly filter the available jobs.
 
Problem: This change resolves the issue reported in #833, where the "Hybrid" filter was not returning the expected results. Now, users selecting the "Hybrid" filter will see the correct available jobs.

Tested on:
   -  Browser: Chrome
   -  Operating System: Windows 11

### CODE REVIEW

File: src/components/FiltreGrup.jsx [hunk 1]
```diff
@@ -160,15 +160,15 @@ const FiltreGrup = () => {
...
+                      value="Hybrid"
                       className="accent-background_green"
-                      checked={fields.remote.includes("hibrid")}
+                      checked={fields.remote.includes("Hybrid")}
                       onChange={(e) => handleCheckBoxChange(e, "remote")}
                     />
-                    <label htmlFor="hibrid" className="pl-1 cursor-pointer">
-                      Hibrid
+                    <label htmlFor="Hybrid" className="pl-1 cursor-pointer">
+                      Hybrid
```
Comment (talidag) [inline src/components/FiltreGrup.jsx:171]: The label shoud be "Hibrid"

Comment (CbnMarian) [reply src/components/FiltreGrup.jsx]: I have updated the label from "Hybrid" to "Hibrid" as requested. Thank you for the feedback!
